# Api-Gateway/src/main/resources/application.properties

spring.application.name=api-gateway
server.port=8089
spring.main.web-application-type=reactive
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs
server.forward-headers-strategy=framework
# Swagger aggregated
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.urls-primary-name=auth-service
springdoc.swagger-ui.urls[0].name=auth-service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs
springdoc.swagger-ui.urls[1].name=user-service
springdoc.swagger-ui.urls[1].url=/users/v3/api-docs
springdoc.swagger-ui.urls[2].name=operator-service
springdoc.swagger-ui.urls[2].url=/operators/v3/api-docs
springdoc.swagger-ui.urls[3].name=payment-service
springdoc.swagger-ui.urls[3].url=/payments/v3/api-docs
springdoc.swagger-ui.urls[4].name=recharge-service
springdoc.swagger-ui.urls[4].url=/recharges/v3/api-docs
springdoc.swagger-ui.urls[5].name=notification-service
springdoc.swagger-ui.urls[5].url=/notifications/v3/api-docs

# Gateway routes docs first
spring.cloud.gateway.routes[0].id=auth-service-docs
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/v3/api-docs,/auth/v3/api-docs/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/auth(?<segment>.*),${segment}

spring.cloud.gateway.routes[1].id=user-service-docs
spring.cloud.gateway.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/v3/api-docs,/users/v3/api-docs/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/users(?<segment>.*),${segment}

spring.cloud.gateway.routes[2].id=payment-service-docs
spring.cloud.gateway.routes[2].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/payments/v3/api-docs,/payments/v3/api-docs/**
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/payments(?<segment>.*),${segment}

spring.cloud.gateway.routes[3].id=operator-service-docs
spring.cloud.gateway.routes[3].uri=lb://OPERATOR-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/operators/v3/api-docs,/operators/v3/api-docs/**
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/operators(?<segment>.*),${segment}

spring.cloud.gateway.routes[4].id=recharge-service-docs
spring.cloud.gateway.routes[4].uri=lb://RECHARGE-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/recharges/v3/api-docs,/recharges/v3/api-docs/**
spring.cloud.gateway.routes[4].filters[0]=RewritePath=/recharges(?<segment>.*),${segment}

spring.cloud.gateway.routes[5].id=notification-service-docs
spring.cloud.gateway.routes[5].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/notifications/v3/api-docs,/notifications/v3/api-docs/**
spring.cloud.gateway.routes[5].filters[0]=RewritePath=/notifications(?<segment>.*),${segment}

# Business routes
spring.cloud.gateway.routes[6].id=auth-service
spring.cloud.gateway.routes[6].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[6].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[7].id=user-service
spring.cloud.gateway.routes[7].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[7].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[8].id=payment-service
spring.cloud.gateway.routes[8].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.routes[8].predicates[0]=Path=/payments/**

spring.cloud.gateway.routes[9].id=notification-service
spring.cloud.gateway.routes[9].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[9].predicates[0]=Path=/notifications/**

spring.cloud.gateway.routes[10].id=recharge-service
spring.cloud.gateway.routes[10].uri=lb://RECHARGE-SERVICE
spring.cloud.gateway.routes[10].predicates[0]=Path=/recharges/**

spring.cloud.gateway.routes[11].id=operator-service
spring.cloud.gateway.routes[11].uri=lb://OPERATOR-SERVICE
spring.cloud.gateway.routes[11].predicates[0]=Path=/operators/**

# Eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Logging
logging.file.name=logs/Api-Gateway.log
logging.level.root=INFO

# JWT
jwt.secret=${JWT_SECRET:secretarjituttt123455667ksfbbfXY}

# Disable devtools
spring.devtools.restart.enabled=false

#
spring.config.activate.on-profile=docker

spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
#eureka.client.service-url.defaultZone=http://service-registry:8761/eureka