
# BASIC CONFIG
# ================================
spring.application.name=api-gateway
server.port=8089
spring.main.web-application-type=reactive

# ================================
# SWAGGER CONFIG (AGGREGATED)
# ================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.urls-primary-name=auth-service

# Aggregated Swagger URLs
springdoc.swagger-ui.urls[0].name=auth-service
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs

springdoc.swagger-ui.urls[1].name=user-service
springdoc.swagger-ui.urls[1].url=/users/v3/api-docs

springdoc.swagger-ui.urls[2].name=operator-service
springdoc.swagger-ui.urls[2].url=/operators/v3/api-docs

springdoc.swagger-ui.urls[3].name=payment-service
springdoc.swagger-ui.urls[3].url=/payments/v3/api-docs

springdoc.swagger-ui.urls[4].name=recharge-service
springdoc.swagger-ui.urls[4].url=/recharges/v3/api-docs

springdoc.swagger-ui.urls[5].name=notification-service
springdoc.swagger-ui.urls[5].url=/notifications/v3/api-docs


# ================================
# GATEWAY ROUTES DOCS FIRST
# ================================
spring.cloud.gateway.server.webflux.enabled=true

# AUTH DOCS
spring.cloud.gateway.server.webflux.routes[0].id=auth-service-docs
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/v3/api-docs,/auth/v3/api-docs/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/auth(?<segment>.*),${segment}

# USER DOCS
spring.cloud.gateway.server.webflux.routes[1].id=user-service-docs
spring.cloud.gateway.server.webflux.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/v3/api-docs,/users/v3/api-docs/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/users(?<segment>.*),${segment}

# PAYMENT DOCS
spring.cloud.gateway.server.webflux.routes[2].id=payment-service-docs
spring.cloud.gateway.server.webflux.routes[2].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/payments/v3/api-docs,/payments/v3/api-docs/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=RewritePath=/payments(?<segment>.*),${segment}

# OPERATOR DOCS
spring.cloud.gateway.server.webflux.routes[3].id=operator-service-docs
spring.cloud.gateway.server.webflux.routes[3].uri=lb://OPERATOR-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/operators/v3/api-docs,/operators/v3/api-docs/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=RewritePath=/operators(?<segment>.*),${segment}

# RECHARGE DOCS
spring.cloud.gateway.server.webflux.routes[4].id=recharge-service-docs
spring.cloud.gateway.server.webflux.routes[4].uri=lb://RECHARGE-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/recharges/v3/api-docs,/recharges/v3/api-docs/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=RewritePath=/recharges(?<segment>.*),${segment}

# NOTIFICATION DOCS
spring.cloud.gateway.server.webflux.routes[5].id=notification-service-docs
spring.cloud.gateway.server.webflux.routes[5].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/notifications/v3/api-docs,/notifications/v3/api-docs/**
spring.cloud.gateway.server.webflux.routes[5].filters[0]=RewritePath=/notifications(?<segment>.*),${segment}


# ================================
# BUSINESS ROUTES
# ================================

# AUTH SERVICE
spring.cloud.gateway.server.webflux.routes[6].id=auth-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/auth/**

# USER SERVICE
spring.cloud.gateway.server.webflux.routes[7].id=user-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/users/**

# PAYMENT SERVICE
spring.cloud.gateway.server.webflux.routes[8].id=payment-service
spring.cloud.gateway.server.webflux.routes[8].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/payments/**

# NOTIFICATION SERVICE
spring.cloud.gateway.server.webflux.routes[9].id=notification-service
spring.cloud.gateway.server.webflux.routes[9].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/notifications/**

# RECHARGE SERVICE
spring.cloud.gateway.server.webflux.routes[10].id=recharge-service
spring.cloud.gateway.server.webflux.routes[10].uri=lb://RECHARGE-SERVICE
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/recharges/**

# OPERATOR SERVICE
spring.cloud.gateway.server.webflux.routes[11].id=operator-service
spring.cloud.gateway.server.webflux.routes[11].uri=lb://OPERATOR-SERVICE
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/operators/**


# ================================
# EUREKA CONFIG
# ================================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Default: Eureka on localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ================================
# LOGGING
# ================================
logging.file.name=logs/Api-Gateway.log
logging.level.root=INFO
logging.level.com.omni=DEBUG

# JWT secret
jwt.secret=${JWT_SECRET:secretarjituttt123455667ksfbbfXY}

# Disable devtools
spring.devtools.restart.enabled=false

#---
# Docker profile overrides
spring.config.activate.on-profile=docker

eureka.client.service-url.defaultZone=http://service-registry:8761/eureka
