spring.application.name=ServiceRegistry
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

#Eureka can see detailed health
management.endpoint.health.show-details=always

logging.file.name=logs/ServiceRegistry.log
logging.level.root=INFO
logging.level.com.omni=DEBUG  