spring.application.name=ConfigServer
server.port=8888

logging.file.name=logs/ConfigServer.log
logging.level.root=INFO
logging.level.com.omni=DEBUG

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Default: Eureka on localhost
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Git config repo
spring.cloud.config.server.git.uri=https://github.com/Callmearjit/config-repo.git
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.timeout=10
spring.cloud.config.server.git.force-pull=true
spring.cloud.config.server.git.skip-ssl-validation=false
spring.cloud.config.server.git.refresh-rate=30

# Disable devtools
spring.devtools.restart.enabled=false

#---
# Docker profile overrides
spring.config.activate.on-profile=docker

eureka.client.service-url.defaultZone=http://service-registry:8761/eureka