spring.application.name=ServiceRegistry
server.port=8761


#Eureka can see detailed health
management.endpoint.health.show-details=always

logging.file.name=logs/ServiceRegistry.log
logging.level.root=INFO
logging.level.com.omni=DEBUG  


# Disable devtools in container
spring.devtools.restart.enabled=false

# Eureka server self-registration stays false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Allow all peers (needed when running in Docker network)
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000