spring.application.name=user-service
server.port=8081

# ==============================
# Config Server (LOCAL)
# ==============================
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false

# ==============================
# Swagger
# ==============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.servers[0].url=http://localhost:8089
springdoc.swagger-ui.servers[0].description=API Gateway

server.forward-headers-strategy=framework

# ==============================
# Eureka (LOCAL)
# ==============================
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ==============================
# Database (LOCAL)
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:5432/OMNI_Recharge
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:root}

# ==============================
# JPA
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==============================
# JWT
# ==============================
jwt.secret=${JWT_SECRET:secretarjituttt123455667ksfbbfXY}

# ==============================
# Devtools
# ==============================
spring.devtools.restart.enabled=false